[package]
name= 'trace'
version= '0.1.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[lib]
path= 'lib.rs'

[dependencies]
cfg-if= ''
fehler= ''
anyhow= ''
rstack-self= {version='', features=["dw"], default-features=false}
signal-hook= {git='https://github.com/Matthias-Fauconneau/signal-hook'}
libc= ''
